### ISSUE TITLE
My Hosting Issue

### ISSUE THREAD

**Issue by LiangCyu1990** [petehouston/app-icons#1]
Hi Pete.
This issue don't related your projects. but I think, you are hosting expert.
My hosting is shared hosting.
I worked with many files(upload and download).
Now I can't work because Disk quota exceeded.
I want you to help me.
best sincerely
![issue](https://user-images.githubusercontent.com/60872168/75674315-c7ded580-5cbf-11ea-99e7-e66758e194ae.png)

**Comment by petehouston** [comment]
You can purchase a bigger plan for your storage hosting need.

**Comment by LiangCyu1990** [comment]
thanks
